import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/layouts/header';
import Footer from '@/components/layouts/footer';
import ScrollToTopButton from '@/components/elements/scrollToTop';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>
                <Header />
                {children}
                <ScrollToTopButton />
                <Footer />
            </body>
        </html>
    );
}
